#ifndef MATRIX_CHAIN_MULTIPLICATION_DEFINES_H
#define MATRIX_CHAIN_MULTIPLICATION_DEFINES_H

#define N 1000
#define INF -1

typedef long long ll;
typedef ll** mat;

#endif //MATRIX_CHAIN_MULTIPLICATION_DEFINES_H
